### PR TITLE
Add Key property to Input

### PR DESCRIPTION
**Pull request by forki**

### CODE REVIEW

**Comment by MangelMaxime** [comment]
Should we add it to all Fields ?

What was the needs being this changes ?

**Comment by forki** [comment]
Yes it needs to go on every element. Sometimes you need to give react a
hint.

Am Di., 8. Jan. 2019, 12:45 hat Maxime Mangel <notifications@github.com>
geschrieben:

**Comment by MangelMaxime** [comment]
Ok, I am trying to merge all the PR and working on Thoth.Json v3 release.

I will merge the PR and release a new version when eveything is working again.

**Comment by forki** [comment]
Cool. Thanks for the hard work.

Am Di., 8. Jan. 2019, 12:55 hat Maxime Mangel <notifications@github.com>
geschrieben:

**Comment by MangelMaxime** [comment]
Thank you for the PR, 

I manually merged it in master.

**Pull request closed without merging**
