### PR TITLE
Remove empty class attributes

### PR DESCRIPTION
**Pull request by kerams**

### CODE REVIEW

**Comment by MangelMaxime** [comment]
Hello @kerams Is it to removed the `" "` which can be generated sometimes?

**Comment by kerams** [comment]
No, it takes care of cases like this:

```fsharp
Tabs.tabs [] [
    Tabs.tab [] [ str "blah" ]
]
```

```html
<div class="tabs">
    <ul>
        <li class>blah</li>
    </ul>
</div>
```

**Comment by MangelMaxime** [comment]
Thank you, it has been released in Fulma 2.12.0

**Comment by kerams** [comment]
;)

**Comment by MangelMaxime** [comment]
I think Github doesn't like the rebase I did on master branch.

I am closing manually the banch but your changes have been added to master

**Pull request closed without merging**
