### PR TITLE
Support bulma-tooltip v3.0.0

### PR DESCRIPTION
**Pull request by kerams**
https://github.com/Wikiki/bulma-tooltip/blob/master/CHANGELOG.md

~~`has-tooltip-active` does not work, but it must be a bug in the tooltip lib itself.~~ Fixed in 3.0.1

What about the docs page? Should I just bump all 2.0.2 references to 3.0.0 or do you want to split version compatibility between v2 and v3 like:

vivaldi_GJik1oZVia

### CODE REVIEW

**Comment by MangelMaxime** [comment]
Thank you @kerams I released it under version 3.0.0 documentation should be available soon too.

For the documentation, I followed what you said.

**Comment by kerams** [comment]
Cheers.

**Comment by kerams** [comment]
Could you please release this on Nuget ;)?

**Comment by MangelMaxime** [comment]
Oups, my bad I had a added a `,` in the changelog and `dotnet` CLI don't like that...

I released it again should be available soon.

**Pull request merged**
