### PR TITLE
Support bulma-timeline

### PR DESCRIPTION
**Pull request by kerams**
https://wikiki.github.io/components/timeline/

Used like (based on the 3rd example in the docs):

```fsharp
Timeline.timeline [ Timeline.IsCentered ] [
    Timeline.Header.header [] [
        Tag.tag [ Tag.Size IsMedium; Tag.Color IsPrimary ] [ str "Start" ]
    ]
    Timeline.Item.item [ Timeline.Item.Color IsPrimary ] [
        Timeline.Item.marker [ Timeline.Item.Marker.Color IsPrimary ] []
        Timeline.Item.content [] [
            p [ Class "heading" ] [ str "January 2016" ]
            p [] [ str "Timeline content - Can include any HTML element" ]
        ]
    ]
    Timeline.Item.item [ Timeline.Item.Color IsWarning ] [
        Timeline.Item.marker [ Timeline.Item.Marker.Color IsWarning; Timeline.Item.Marker.IsImage; Timeline.Item.Marker.Is32x32 ] [
            img [ Src "https://bulma.io/images/placeholders/32x32.png" ]
        ]
        Timeline.Item.content [] [
            p [ Class "heading" ] [ str "February 2016" ]
            p [] [ str "Timeline content - Can include any HTML element" ]
        ]
    ]
    Timeline.Header.header [] [
        Tag.tag [ Tag.Color IsPrimary ] [ str "2017" ]
    ]
    Timeline.Item.item [ Timeline.Item.Color IsDanger ] [
        Timeline.Item.marker [ Timeline.Item.Marker.Color IsDanger; Timeline.Item.Marker.IsIcon ] [
            Fa.i [ Fa.Solid.Flag ] []
        ]
        Timeline.Item.content [] [
            p [ Class "heading" ] [ str "March 2017" ]
            p [] [ str "Timeline content - Can include any HTML element" ]
        ]
    ]
    Timeline.Header.header [] [
        Tag.tag [ Tag.Size IsMedium; Tag.Color IsPrimary ] [ str "End" ]
    ]
]
```

Docs page incoming soon.

### CODE REVIEW

**Comment by kerams** [comment]
I cannot get the docs to build with `fake build -t watchdocs`. `docs.fsproj` expects `src/Fulma/Versions.fs`, which does not exist. If I comment it you, there's a million errors like this

```
ERROR in ./docs/src/Fulma/Layout/Columns.fs (./docs/custom-loader.js?line=117!./docs/src/Fulma/Layout/Columns.fs) 1:17
Module parse failed: Unterminated string constant (1:17)
File was processed with these loaders:
 * ./docs/custom-loader.js
You may need an additional loader to handle the result of these loaders.
\n                (Widgets.Showcase.view (fun _ -> ofType<GapSize,_,_> (unbox null) [ ]) (Render.includeCode __LINE__ __"n                 ]\"\"\"lumn.IsFull)3)n
 @ ./docs/src/Fulma/Layout/Columns.fs 16:0-75 92:5-22
 @ ./docs/src/Fulma/Router.fs
 @ ./docs/src/App.fs
 @ ./docs/docs.fsproj
 @ multi ./docs/docs.fsproj
```

**Comment by MangelMaxime** [comment]
Hello, 
thank you for your work.

I am taking a look at the problem.

**Comment by kerams** [comment]
By the way, are you OK with how the element builders and option DUs are nested in modules?

**Comment by MangelMaxime** [comment]
Yes, it seems good to me.

Can you please check if the documentation generation is now fixed on your side too?

**Comment by kerams** [comment]
It is, thanks.

**Comment by MangelMaxime** [comment]
Thank you for your work @kerams 

Version 1.0.0 has been released :)

**Pull request merged**
