### PR TITLE
Update dependencies - Elmish.React, Fable.React

### PR DESCRIPTION
**Pull request by kerams**
I'm having issues in VS because not all projects are included in the solution file (I assume you use Ionide).

Running `fake.cmd build` passes without problems, can you please double check too?

### CODE REVIEW

**Comment by MangelMaxime** [comment]
Hello @kerams,
thank you for the PR.

I am indeed using Ionide, but if some projects need to be added to the sln file I am fine with that.

In order, to test the change I need to update a few Elmish packages however there is one package I don't have owner ship. I am asking Eugene to give me access to it and as soon as I have I will continue the work on this PR.

**Comment by MangelMaxime** [comment]
Thank you @kerams 

I released beta version of all the packages with the latest changes made @alfonsogarciacaro to split the Fable.React.Types repo in 2.

https://github.com/fable-compiler/fable-react/pull/234

**Comment by MangelMaxime** [comment]
I pushed your changes to master directly, but seems like Github didn't consider that PR merge for some reason 🤷‍♂️

**Comment by kerams** [comment]
It's alright, thanks.

**Pull request closed without merging**
